version: '1.0'

networks:
  dev:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    networks:
      - dev
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/logs
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./.logs/postgres:/logs


  webapp:
    container_name: webapp
    build: server/
    # restart: unless-stopped
    networks:
      - dev
    command: bash -c "python support/load_to_postgres.py && python main.py"
    # command: gunicorn --bind 0.0.0.0:5000 main:app
    ports:
      - "5000:5000"
    depends_on:
      - postgres


  nginx:
      container_name: nginx
      image: nginx:latest
      # restart: unless-stopped
      networks:
        - dev
      ports:
        - "8080:80"
      volumes:
        - ./server/conf:/etc/nginx/conf.d
        - ./.logs/nginx:/var/log/nginx
      depends_on:
        - webapp

  # image: registry.gitlab.com/excobalt/mlops:latest
